-- Configuración de habilidades y reputación
Config = {}

Config.Debug = true

Config.SkillMenuCommand = 'habilidades'
Config.SkillMenuCommandDescription = 'Ver tus habilidades actuales o reputación laboral!'

-- Menú principal de habilidades
Config.SkillMenu = {
    MainTitle = 'Habilidades y Reputacion',
    SkillsMenuTitle = 'Habilidades',
    SkillMenuDescription = 'Ver tus habilidades.',
    SkillMenuIconColor = 'gold',
    ReputationMenuTitle = 'Reputación Laboral',
}

-- Menú principal de reputación
Config.ReputationMenu = {
    Title = 'Reputación Laboral',
    Description = 'Ver tu reputación laboral.',
    Icon = 'fa-solid fa-briefcase',
    IconColor = 'green',
}
------------------------------------

Config.SkillMenuTitleInner = 'Niveles de Habilidad'

Config.Skills = {
    -- ILEGAL
    {   title = 'Fabricación de Drogas',
        categorySkill = 'ilegal',
        Icon = 'fa-solid fa-cannabis',
        IconColour = 'gold',
        Rep = 'drogas',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Robo a Mano Armada',
        categorySkill = 'ilegal',
        Icon = 'fa-solid fa-dice',
        IconColour = 'gold',
        Rep = 'robo',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Asesinatos',
        categorySkill = 'ilegal',
        Icon = 'fa-solid fa-skull',
        IconColour = 'gold',
        Rep = 'asesinato',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Planificacion de robos',
        categorySkill = 'ilegal',
        Icon = 'fa-solid fa-gamepad',
        IconColour = 'gold',
        Rep = 'planificacionderobos',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Corrupcion',
        categorySkill = 'ilegal',
        Icon = 'fa-solid fa-dumpster-fire',
        IconColour = 'gold',
        Rep = 'corrupcion',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Contrabando',
        categorySkill = 'ilegal',
        Icon = 'fa-solid fa-bezier-curve',
        IconColour = 'gold',
        Rep = 'contrabando',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Sustancias ilegales',
        categorySkill = 'ilegal',
        Icon = 'fa-solid fa-person-falling-burst',
        IconColour = 'gold',
        Rep = 'sustanciasilegales',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Bebidas prohibidos',
        categorySkill = 'ilegal',
        Icon = 'fa-solid fa-ban',
        IconColour = 'gold',
        Rep = 'bebidasprohibidos',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Falsificacion',
        categorySkill = 'ilegal',
        Icon = 'fa-solid fa-copy',
        IconColour = 'gold',
        Rep = 'falsificacion',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Decodificacion de documentos',
        categorySkill = 'ilegal',
        Icon = 'fa-solid fa-file-contract',
        IconColour = 'gold',
        Rep = 'decodificaciondedocumentos',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Saqueo',
        categorySkill = 'ilegal',
        Icon = 'fa-solid fa-people-robbery',
        IconColour = 'gold',
        Rep = 'saqueo',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    -- CONOCIMIENTO
    {   title = 'Investigacion',
        categorySkill = 'conocimiento',
        Icon = 'fa-solid fa-magnifying-glass-plus',
        IconColour = 'gold',
        Rep = 'investigacion',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Exploracion',
        categorySkill = 'conocimiento',
        Icon = 'fa-solid fa-eye',
        IconColour = 'gold',
        Rep = 'exploracion',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Logistica',
        categorySkill = 'conocimiento',
        Icon = 'fa-solid fa-road',
        IconColour = 'gold',
        Rep = 'logistica',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Lectura',
        categorySkill = 'conocimiento',
        Icon = 'fa-solid fa-book',
        IconColour = 'gold',
        Rep = 'lectura',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Escritura',
        categorySkill = 'conocimiento',
        Icon = 'fa-solid fa-pencil',
        IconColour = 'gold',
        Rep = 'escritura',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Diseño',
        categorySkill = 'conocimiento',
        Icon = 'fa-solid fa-palette',
        IconColour = 'gold',
        Rep = 'diseño',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Finanzas',
        categorySkill = 'conocimiento',
        Icon = 'fa-solid fa-ranking-star',
        IconColour = 'gold',
        Rep = 'finanzas',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Negociacion',
        categorySkill = 'conocimiento',
        Icon = 'fa-solid fa-file-signature',
        IconColour = 'gold',
        Rep = 'negociacion',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Comercio',
        categorySkill = 'conocimiento',
        Icon = 'fa-solid fa-comments-dollar',
        IconColour = 'gold',
        Rep = 'comercio',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Comunicacion',
        categorySkill = 'conocimiento',
        Icon = 'fa-solid fa-bullhorn',
        IconColour = 'gold',
        Rep = 'comunicacion',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Gestion',
        categorySkill = 'conocimiento',
        Icon = 'fa-solid fa-check-to-slot',
        IconColour = 'gold',
        Rep = 'gestion',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Tratamientos',
        categorySkill = 'conocimiento',
        Icon = 'fa-solid fa-capsules',
        IconColour = 'gold',
        Rep = 'tratamientos',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Diagnostico',
        categorySkill = 'conocimiento',
        Icon = 'fa-solid fa-stethoscope',
        IconColour = 'gold',
        Rep = 'diagnostico',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    -- MANUALES
    {   title = 'Mecanica',
        categorySkill = 'manuales',
        Icon = 'fa-solid fa-gear',
        IconColour = 'gold',
        Rep = 'mecanica',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Explosivos',
        categorySkill = 'manuales',
        Icon = 'fa-solid fa-fire-burner',
        IconColour = 'gold',
        Rep = 'explosivos',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Modificacion de armas',
        categorySkill = 'manuales',
        Icon = 'fa-solid fa-oil-can',
        IconColour = 'gold',
        Rep = 'modificaciondearmas',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Forja de armas',
        categorySkill = 'manuales',
        Icon = 'fa-solid fa-cannabis',
        IconColour = 'gold',
        Rep = 'forjadearmas',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Fabricación',
        categorySkill = 'manuales',
        Icon = 'fa-solid fa-hand',
        IconColour = 'gold',
        Rep = 'fabricacion',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Peleteria',
        categorySkill = 'supervivencia',
        Icon = 'fa-solid fa-hand-dots',
        IconColour = 'gold',
        Rep = 'peleteria',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Alquimia',
        categorySkill = 'manuales',
        Icon = 'fa-solid fa-book-quran',
        IconColour = 'gold',
        Rep = 'alquimia',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Herreria',
        categorySkill = 'manuales',
        Icon = 'fa-solid fa-road-spikes',
        IconColour = 'gold',
        Rep = 'herreria',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Costura',
        categorySkill = 'manuales',
        Icon = 'fa-solid fa-circle-half-stroke',
        IconColour = 'gold',
        Rep = 'costura',
        ProgressColour = 'gold',
        skillargs = {},
    },
    {   title = 'Carpinteria',
        categorySkill = 'supervivencia',
        Icon = 'fa-solid fa-tree',
        IconColour = 'gold',
        Rep = 'carpinteria',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Mineria',
        categorySkill = 'supervivencia',
        Icon = 'fa-solid fa-tower-observation',
        IconColour = 'gold',
        Rep = 'mineria',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Medicina',
        categorySkill = 'manuales',
        Icon = 'fa-solid fa-notes-medical',
        IconColour = 'gold',
        Rep = 'medicina',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Cocina',
        categorySkill = 'supervivencia',
        Icon = 'fa-solid fa-plate-wheat',
        IconColour = 'gold',
        Rep = 'cocina',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    -- SUPERVIVIENCIA
    {   title = 'Suerte',
        categorySkill = 'conocimiento',
        Icon = 'fa-solid fa-dice',
        IconColour = 'gold',
        Rep = 'suerte',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Primeros auxilios pets',
        categorySkill = 'manuales',
        Icon = 'fa-solid fa-user-nurse',
        IconColour = 'gold',
        Rep = 'primerosauxiliospets',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Primeros auxilios',
        categorySkill = 'manuales',
        Icon = 'fa-solid fa-heart',
        IconColour = 'gold',
        Rep = 'primerosauxilios',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    
    {   title = 'Polinizacion',
        categorySkill = 'supervivencia',
        Icon = 'fa-solid fa-mountain',
        IconColour = 'gold',
        Rep = 'polinizacion',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Cria de animales',
        categorySkill = 'supervivencia',
        Icon = 'fa-solid fa-kiwi-bird',
        IconColour = 'gold',
        Rep = 'criadeanimales',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Ganaderia',
        categorySkill = 'supervivencia',
        Icon = 'fa-solid fa-cow',
        IconColour = 'gold',
        Rep = 'ganaderia',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Doma caballo',
        categorySkill = 'supervivencia',
        Icon = 'fa-solid fa-horse',
        IconColour = 'gold',
        Rep = 'domacaballo',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
            { Level = 15, Label = 'Nivel 15', Value = 'Fabricar avd' },
            { Level = 20, Label = 'Nivel 20', Value = 'Fabricar exp' },
        },
    },
    {   title = 'Doma bestia',
        categorySkill = 'supervivencia',
        Icon = 'fa-solid fa-staff-snake',
        IconColour = 'gold',
        Rep = 'domabestia',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Trapero',
        categorySkill = 'supervivencia',
        Icon = 'fa-solid fa-otter',
        IconColour = 'gold',
        Rep = 'trapero',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Pesca',
        categorySkill = 'supervivencia',
        Icon = 'fa-solid fa-fish-fins',
        IconColour = 'gold',
        Rep = 'pesca',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Caza',
        categorySkill = 'supervivencia',
        Icon = 'fa-solid fa-paw',
        IconColour = 'gold',
        Rep = 'caza',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Cultivo',
        categorySkill = 'supervivencia',
        Icon = 'fa-solid fa-tractor',
        IconColour = 'gold',
        Rep = 'cultivo',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    {   title = 'Recolector',
        categorySkill = 'supervivencia',
        Icon = 'fa-solid fa-leaf',
        IconColour = 'gold',
        Rep = 'recolector',
        ProgressColour = 'gold',
        skillargs = {
            { Level = 10, Label = 'Nivel 10', Value = 'Fabricar' },
        },
    },
    -- Agregar más habilidades aquí
}

Config.JobReputationMenuTitle = 'Reputación Laboral'

Config.JobReputations = {
    {   title = 'Unemployed',
        Icon = 'fa-solid fa-face-smile',
        IconColour = 'silver',
        categoryJob = 'miscelanea',
        Rep = 'unemployed',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillRep = {
            } ]]
        },
    },
    {   title = 'Juez',
        Icon = 'fa-solid fa-hand',
        IconColour = 'silver',
        categoryJob = 'legal y medica',
        Rep = 'judge',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ Skills = {

            }, ]]
        },
    },
    {   title = 'Gobernador',
        Icon = 'fa-solid fa-flag-usa',
        IconColour = 'silver',
        categoryJob = 'legal y medica',
        Rep = 'governor',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillRep = {
                'comunicacion',
                'administracion',
                'honor',
                'gestion',
                'manipulacion',
                'corrupcion'
            } ]]
        },
    },
    {   title = 'Doma',
        Icon = 'fa-solid fa-dog',
        IconColour = 'silver',
        categoryJob = 'fauna y flora',
        Rep = 'horse_trainer',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
--[[             SkillRep = {
                'domabestia',
                'domapets',
                'domacaballo',
                'equitacion'
            } ]]
        },
    },
    {   title = 'Cazador',
        Icon = 'fa-solid fa-drumstick-bite',
        IconColour = 'silver',
        categoryJob = 'fauna y flora',
        Rep = 'hunter',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillRep = {
                'peleteria',
                --'taxidermia',
                'trapero',
                'pesca',
                'caza'
            } ]]
        },
    },
    {   title = 'Cocinero',
        Icon = 'fa-solid fa-pepper-hot',
        IconColour = 'silver',
        categoryJob = 'fabricacion',
        Rep = 'cook',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillRep = {
                'sustanciasilegales',
                'platosprohibidos',
                'mezcladesabores',
                'alquimia',
                'cocina'
            } ]]
        },
    },
    {   title = 'Tabernero',
        Icon = 'fa-solid fa-people-roof',
        IconColour = 'silver',
        categoryJob = 'miscelanea',
        Rep = 'innkeeper',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillRep = {
                'bebidasprohibidos'
            } ]]
        },
    },
    {   title = 'Agricultor',
        Icon = 'fa-solid fa-wheat-awn',
        IconColour = 'silver',
        categoryJob = 'fauna y flora',
        Rep = 'farmer',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillRep = {
                'polinizacion',
                'criadeanimales',
                'ganaderia',
                'cultivo',
                'recolector'
            } ]]
        },
    },
    {   title = 'Ganadero',
        Icon = 'fa-solid fa-cow',
        IconColour = 'silver',
        categoryJob = 'fauna y flora',
        Rep = 'rancher',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillRep = {
            } ]]
        },
    },
    {   title = 'Apicultor',
        Icon = 'fa-solid fa-bugs',
        IconColour = 'silver',
        categoryJob = 'fauna y flora',
        Rep = 'beekeeper',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillRep = {
            } ]]
        },
    },
    {   title = 'Medico',
        Icon = 'fa-solid fa-briefcase-medical',
        IconColour = 'silver',
        categoryJob = 'legal y medica',
        Rep = 'doctor',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillRep = {
                'primerosauxiliospets',
                'diagnostico',
                'tratamientos',
                'primerosauxilios',
                'medicina'
            } ]]
        },
    },
    {   title = 'Veterinario',
        Icon = 'fa-solid fa-bone',
        IconColour = 'silver',
        categoryJob = 'legal y medica',
        Rep = 'veterinarian',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillRep = {
            } ]]
        },
    },
    {   title = 'Enterrador',
        Icon = 'fa-solid fa-skull-crossbones',
        IconColour = 'silver',
        categoryJob = 'miscelanea',
        Rep = 'undertaker',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillRep = {
            } ]]
        },
    },
    {   title = 'Modista',
        Icon = 'fa-solid fa-sliders',
        IconColour = 'silver',
        categoryJob = 'fabricacion',
        Rep = 'seamstress',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillRep = {
                'sastreria',
                'costura'
            } ]]
        },
    },
    {   title = 'Herrero',
        Icon = 'fa-solid fa-magnet',
        IconColour = 'silver',
        categoryJob = 'fabricacion',
        Rep = 'blacksmith',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillRep =  {
                'forjadearmas',
                'fundicion',
                'mineria',
                'herreria'
            } ]]
        },
    },
    {   title = 'Armero',
        Icon = 'fa-solid fa-gun',
        IconColour = 'silver',
        categoryJob = 'fabricacion',
        Rep = 'gunsmith',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillRep = {
                'modificaciondearmas',
                'armeria'
            } ]]
        },
    },
    {   title = 'Relojero',
        Icon = 'fa-solid fa-alarm-clock',
        IconColour = 'silver',
        categoryJob = 'fabricacion',
        Rep = 'watchmaker',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillRep = {
                'fabricaciondearmas',
                'fabricacion',
                'explosivos',
                'mecanica'
            } ]]
        },
    },
    {   title = 'Joyero',
        Icon = 'fa-solid fa-dice-d20',
        IconColour = 'silver',
        categoryJob = 'fabricacion',
        Rep = 'jeweler',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillRep = {
                'contrabando',
                'diseño',
            } ]]
        },
    },
    {   title = 'Escriba',
        Icon = 'fa-solid fa-pen-nib',
        IconColour = 'silver',
        categoryJob = 'miscelanea',
        Rep = 'scribe',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillRep = {
                'falsificacion',
                'redacciondedocumentos',
                'escritura',
                'lectura',
            } ]]
        },
    },
    {   title = 'Construccion',
        Icon = 'fa-solid fa-city',
        IconColour = 'silver',
        categoryJob = 'fabricacion',
        Rep = 'construction_worker',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillRep = {
                'carpinteria'
            } ]]
        },
    },
    {   title = 'Busca tesoros',
        Icon = 'fa-solid fa-magnifying-glass',
        IconColour = 'silver',
        categoryJob = 'miscelanea',
        Rep = 'treasure_hunter',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillsRep = {
                'exploracion',
                'Decodificacion de documentos',
                'saqueo'
            }, ]]
        },
    },
    {   title = 'Transportista',
        Icon = 'fa-solid fa-truck-fast',
        IconColour = 'silver',
        categoryJob = 'miscelanea',
        Rep = 'transporter',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillRep = {
                'logistica',
                'conduccion'
            } ]]
        },
    },
    {   title = 'Comerciante',
        Icon = 'fa-solid fa-scale-unbalanced-flip',
        IconColour = 'silver',
        categoryJob = 'miscelanea',
        Rep = 'merchant',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillRep =  {
                'finanzas',
                'negociacion',
                'comercio'
            } ]]
        },
    },
    {   title = 'Policia',
        Icon = 'fa-solid fa-star',
        IconColour = 'silver',
        categoryJob = 'legal y medica',
        Rep = 'police',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillRep = {
                'tacticasdearresto',
                'suerte',
                'investigacion',
            } ]]
        },
    },
    {   title = 'Guardia de prisiones',
        Icon = 'fa-solid fa-scroll',
        IconColour = 'silver',
        categoryJob = 'legal y medica',
        Rep = 'prison_guard',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillRep = {
            } ]]
        },
    },
    {   title = 'Criminal',
        Icon = 'fa-solid fa-ghost',
        IconColour = 'silver',
        categoryJob = 'miscelanea',
        Rep = 'criminal',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillsRep = {
                'drogas',
                'robo',
                'asesinato',
                'delincuencia',
                'planificacionderobos'
            }, ]]
        },
    },
    {   title = 'Cazarecompensas',
        Icon = 'fa-solid fa-book-skull',
        IconColour = 'silver',
        categoryJob = 'legal y medica',
        Rep = 'bounty_hunter',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillsRep = {
                'drogas',
                'robo',
                'asesinato',
                'delincuencia',
                'planificacionderobos'
            }, ]]
        },
    },
    {   title = 'Abogado',
        Icon = 'fa-solid fa-stamp',
        IconColour = 'silver',
        categoryJob = 'legal y medica',
        Rep = 'lawyer',
        ProgressColour = 'orange',
        repargs = {
            LevelRange = 'Level 1-5',
            Value = 'Quick processes and more returns',
            --[[ SkillRep = {
            } ]]
        },
    },
    -- Agregar más reputaciones aquí
}
